### PR TITLE
Moved all event handlers and related code out of control.lua and into eventhandlers.lua

### PR DESCRIPTION
**Pull request by petergaultney**
Refactored a fair amount of the code.

Changed indenting. 4 spaces, as agreed! ;)

Semantics have barely changed at all - I tested for a few minutes and everything still seems to work.

### CODE REVIEW

**Comment by petergaultney** [comment]
one thing I should mention - the only code I truly rearranged was at the top of runTickTableUpdates. There was some code that ensured that there was an updateTable for each force - even the 'enemy' and 'neutral' forces.

I don't see anywhere in the code where we would ever try to put anything in (or access anything in) a table for a force that is neutral or enemy. So I moved this check into the global_fixupTickTablesForForceName function, where it will only ever run for forces that might have entities we'd want to interact with.  It makes the code look cleaner, and there didn't seem to be any need to create a table we'd never use.

If I'm incorrect, and there are cases where we might want an updateTable for an enemy or neutral force, even though the corresponding per-tick entries in that table were never created by the previous code, then we need to undo that particular change.

**Comment by kyranf** [comment]
@petergaultney  the game starts by default every time 3 forces - "player", "enemy" which the biters default to using, and "neutral" which I think is where dead/godmode players go, but i'm not sure about that. 

The code in the ticktable handler is indiscriminate  - in fact, almost all code that handles forces also iterates through the "enemy" and "neutral" but there's usually nothing in them (squad tables are empty, but at least not nil, for example) so it just moves on to the next force. 

The code just looks out of place because i explicitly mention the force names rather than just doing a "for each force..." section of code. Perhaps we/i should just change it to be like that anyway. 

I added the code because I was getting errors at the time and I know the game ALWAYS has those forces available (and the force created event doesn't trigger for them, which is the main point here actually) so I set them up explicitly.

**Comment by petergaultney** [comment]
yeah, I think I understand the existence of the various forces. But I don't think we ever actually *access* global.updateTable['enemy'], for instance. The only place we iterate over all existing forces and check their updateTables is in the runTickTableUpdates function.

so I guess I'm saying I don't think we need to create the tick table for the enemy and neutral forces, because we never try to access those tables later on. In fact, it seems to me we might be better off without creating those tables (as long as the code doesn't crash, of course -- which for me at least it doesn't), simply because I'd rather know if the code were accidentally trying to put Squads in tick tables belonging to the enemy or to the neutral player.

**Comment by kyranf** [comment]
you are right, the code never directly has " global.updateTable["enemy"] "  but the table IS access during the following example (not from the real code, i am just writing it offhand now):

for _, force in pairs(game.forces) do
    local tickTable = global.updateTable[force.name]
end

That will iterate through all forces in the game (the default 3, unless someone makes more forces in a PvP scenario for example) and access the global updateTable for each one. There might be a check later like "if tickTable then ...  end"   or whatever, but the point is, those tables WILL be accessed or at least checked for validity even if the mod doesn't currently make use of them. 

I was getting errors for accessing those nil tables during my testing, that is why I added them, so at least at one point my code was doing that. I mean, a simple one-liner can be added to check if it's nil and then move on if it is. But what if that misses a valid, good force that was meant to be processed or set up later? Anyway this stuff is certainly something that can be cleaned up/clarified so it's good that you have found/noticed it :)  

Hopefully tonight I can  pull the code and test it on my end.

**Comment by petergaultney** [comment]
yep, for sure. I do agree that if we ever did iterate over the forces somewhere else and didn't want to check what forces they were, we certainly wouldn't want null access issues. Basically just wanted to make sure I wasn't missing something (sounds like I'm not), but I'm okay with making empty tables in order to allow us to iterate over empty sets.

**Comment by petergaultney** [comment]
closing this one as superseded by https://github.com/kyranf/robotarmyfactorio/pull/69

**Pull request closed without merging**
