### PR TITLE
2.0 migration

### PR DESCRIPTION
**Pull request by cyril-orlov**
Hey, did a migration of your mod for a friend. Some gameplay testing done, but no warranty ofc. Removed README aswell, need to roll it back before merging.

### CODE REVIEW

**Comment by kyranf** [comment]
This is fantastic, thank you very much for this work. I will review the changes and do some play testing for validation. Probably over the next week or so. 

If you happen to have time, a similar work to port the code on branch `5.0` would be appreciated too. It's a simpler (code), newer, improved and new stuff version of the mod which was very close to release but didn't quite make it.  If that was ported to work for v2.0 of Factorio, I could do the final touches on it and release that too!

**Comment by cyril-orlov** [comment]
If you find these changes good for the master branch, I'll try rolling them over to 5.0 aswell. The two branches have 100+ combined commit difference however; even cherrypicking the migration commit makes for a dozen conflicted files.

**Comment by kyranf** [comment]
> If you find these changes good for the master branch, I'll try rolling them over to 5.0 aswell. The two branches have 100+ combined commit difference however; even cherrypicking the migration commit makes for a dozen conflicted files.

The problem as you've mentioned is that v5.0 of Robot Army is a massive overhaul and clean-up of the code. A lot of stuff isn't there anymore. It's likely easier to clean up, but similar in many ways in the assets. There is no hope at all really in cherrypicking changes, it would need to be a manual process  similar (but likely less work) to the first round of fixes for v4.x

**Comment by cyril-orlov** [comment]
Well, since the migration process was mostly API renames (e.g. ```global```->```storage```) and data restructuring (e.g. ```{"steel-plate", 5}``` -> ```{type="item", name="steel-plate", amount=5}```, shouldn't be a major issue. After we are done here, I'll give 5.0 a look if I can.

**Pull request merged**
